### ISSUE TITLE
Lanelet2 Map Serialization not portable

### ISSUE THREAD

**Issue by rowandempster** [Autoware-AI/common#20]
### Required information:

- Operating system and version: Ubuntu 20 and Ubuntu 18
  - 
- Autoware installation type: Built lanelet2_extension from source
  - 
- Autoware version or commit hash: Latest develop
  - 
- ROS distribution and version: Noetic (on Ubuntu 20) and Melodic (on Ubuntu 18)
  - 
- ROS installation type: Docker
  - 
- Package or library, if applicable: lanelet2_extension
  - 

### Description of the bug

A lanelet2 map that is serialized (see https://github.com/Autoware-AI/common/blob/master/lanelet2_extension/lib/message_conversion.cpp#L52) on the Ubuntu 20 machine cannot be deserialized (see https://github.com/Autoware-AI/common/blob/master/lanelet2_extension/lib/message_conversion.cpp#L76) on the Ubuntu 18 machine because `boost::archive::binary_iarchive` is not portable. Specifically:
```
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  unsupported version
```

Would it be possible to switch the serialization to `text_iarchive`/`text_oarchive` or would that be too much on a hit on performance?

**Comment by rowandempster** [comment]
Tagging file authors, @simon-t4 @mitsudome-r

**Comment by rowandempster** [comment]
Hmm actually I just tried out `text_iarchive` and same thing. I guess the issue is just incompatibility between archiving in Boost `Version: 1.65.1.0` (Ubuntu 18) and `Version: 1.71.0.0` (Ubuntu 20)

**Comment by mitsudome-r** [comment]
I don't think ROS in general does not assume communication between different versions.
Even if you were able to install same version of boost, there could be many other issues due to difference in ROS version so I would strongly recommend using same version.
