### ISSUE TITLE
laserscan2costmap provides a map with wrong orientation

### ISSUE THREAD

**Issue by kosmastsk** [Autoware-AI/common#7]
Ubuntu 18.04
Autoware 1.13 installed from source following the wiki page
`git rev-parse HEAD` : e91b3e09f4e381819b67de61db77b9360dbbc981 
ROS Melodic 
package related: `object_map`

### Description of the bug
When I try to create a costmap from my laserscan, the orientation of the /ring_ogm is not correct. Is it rotated with regards to the sensor frame. This has also been mentioned in [this](https://github.com/Autoware-AI/autoware.ai/issues/2218) issue.

### Steps to reproduce the bug
1. Launch runtime manager and enable RViZ and laserscan2costmap node from the Computing tab.
2. Load [this bag](https://drive.google.com/file/d/1yoUEHueiPdiAF5jWqdv-caoeTtAdXufX/view?usp=sharing) in the Simulation tab. 
3. In the laserscan2costmap node, set as scan topic `/front_laser/scan' and as sensor frame: `front_laser_base_link`
4. In RViZ visualize the `/front_laser/scan` and the `ogm_ring` topics.
5. Run the ROSbag

### Expected behavior
The costmap should be rotated anticlockwise 90 degrees to match the sensor frame.

### Screenshots
The result is depicted in the image below: 
![Screenshot from 2020-07-17 09-43-16](https://user-images.githubusercontent.com/18221518/87757583-8fc1d480-c813-11ea-91e9-7d0b4a447a76.png)

**Comment by JWhitleyWork** [comment]
@kosmastsk This is not a confirmed bug and will require troubleshooting. Please post on [ROS Answers](https://answers.ros.org/) with the tag `autoware` per our [Support Guidelines](https://github.com/Autoware-AI/autoware.ai/wiki/Support-guidelines) and the community (probably me) will help you there.
